import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SeoService } from '../../services/seo.service';

@Component({
  selector: 'app-terms-of-service',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="legal-page-wrapper">
      <div class="legal-hero">
        <div class="legal-container">
          <div class="legal-breadcrumb">
            <a routerLink="/"><i class="fa-solid fa-house"></i> Home</a>
            <span>/</span>
            <span>Legal</span>
            <span>/</span>
            <span class="active">Terms of Service</span>
          </div>
          <h1 class="legal-title">Terms of Service</h1>
          <p class="legal-meta">Effective Date: August 29, 2026 · Sunsolv Technologies</p>
        </div>
      </div>

      <div class="legal-container legal-content-grid">
        <div class="legal-main-body">
          <div class="legal-intro-box">
            <p>
              Welcome to <strong>Sunsolv Technologies</strong> ("Sunsolv", "we", "our", or "us"). These Terms of Service ("Terms") govern your access to and use of our website (<strong>sunsolv.in</strong> / <strong>sunsolv.com</strong>), the online <em>Business Solution Finder</em> diagnostic, consultation scheduling systems, and all associated technical consulting, cloud engineering, AI automation, and custom software development services.
            </p>
          </div>

          <section class="legal-section" id="acceptance">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing our website, submitting an enquiry via the Solution Finder, booking a strategy consultation, or engaging Sunsolv Technologies for development services, you agree to be bound by these Terms and our Privacy Policy. If you do not agree, please do not use our services.
            </p>
          </section>

          <section class="legal-section" id="services">
            <h2>2. Scope of Services & Solution Finder</h2>
            <p>Sunsolv Technologies provides comprehensive digital transformation and engineering services, including:</p>
            <ul>
              <li><strong>Business Solution Finder:</strong> An exploratory diagnostic tool designed to provide preliminary technical architecture blueprints, suggested modular scopes, and indicative budget ranges.</li>
              <li><strong>Technical Consultation:</strong> 1-on-1 discovery calls with Senior Technical Solution Architects to refine requirements and build detailed Master Services Agreements (MSA) or Statements of Work (SOW).</li>
              <li><strong>Engineering Deliverables:</strong> Custom web platforms, SaaS applications, mobile apps (iOS/Android), AI agents and workflow automations, cloud migrations (AWS/GCP), custom ERP/CRM systems, and growth optimization.</li>
            </ul>
            <div class="legal-callout info">
              <i class="fa-solid fa-circle-info"></i>
              <div>
                <strong>Indicative Nature of Diagnostic Blueprints:</strong> Blueprints and investment estimates generated by the Solution Finder are non-binding architectural recommendations intended to guide discovery. Formal scopes and deliverables are finalized exclusively in a signed Statement of Work (SOW).
              </div>
            </div>
          </section>

          <section class="legal-section" id="ip-rights">
            <h2>3. Intellectual Property Rights</h2>
            <ul>
              <li><strong>Client Deliverables & Data:</strong> Upon full payment of all contracted fees, the client retains 100% ownership of bespoke source code, custom assets, databases, and proprietary business logic developed specifically for the client under an active SOW.</li>
              <li><strong>Sunsolv Pre-Existing IP:</strong> Sunsolv retains ownership of its proprietary frameworks, reusable starter kits, boilerplates, libraries, diagnostic algorithms, and pre-existing tools used to build deliverables. Clients receive a perpetual, non-exclusive license to use any embedded pre-existing components necessary for the operation of their software.</li>
              <li><strong>Website Materials:</strong> All text, graphics, logos, icons, and software on this website are the intellectual property of Sunsolv Technologies and are protected by copyright and trademark laws.</li>
            </ul>
          </section>

          <section class="legal-section" id="client-responsibilities">
            <h2>4. Client Responsibilities & User Conduct</h2>
            <p>When using our website and diagnostic tools, you agree to:</p>
            <ul>
              <li>Provide accurate, genuine, and lawful corporate information and project requirements.</li>
              <li>Ensure you possess all necessary rights and authorizations for any digital assets, designs, codebases, or documents uploaded to our platform.</li>
              <li>Refrain from attempting to reverse-engineer, disrupt, or introduce malicious code into our systems or network infrastructure.</li>
            </ul>
          </section>

          <section class="legal-section" id="confidentiality">
            <h2>5. Confidentiality & Non-Disclosure</h2>
            <p>
              We treat all client project ideas, technical specifications, and proprietary business information shared during the diagnostic and consultation phases with the highest standard of confidentiality. We routinely execute mutual Non-Disclosure Agreements (NDAs) prior to in-depth architecture discussions.
            </p>
          </section>

          <section class="legal-section" id="warranties">
            <h2>6. Warranties & Disclaimers</h2>
            <p>
              Our website, Solution Finder, and initial consultations are provided on an "AS IS" and "AS AVAILABLE" basis. While we strive for absolute technical accuracy, Sunsolv Technologies makes no express or implied warranties regarding uninterrupted website availability, instant business revenue outcomes, or third-party API uptime beyond contracted Service Level Agreements (SLAs) defined in custom contracts.
            </p>
          </section>

          <section class="legal-section" id="liability">
            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Sunsolv Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business interruption arising out of your use of the website or diagnostic tools.
            </p>
          </section>

          <section class="legal-section" id="governing-law">
            <h2>8. Governing Law & Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>. Any disputes arising out of or in connection with these Terms or services provided by Sunsolv Technologies shall be subject to the exclusive jurisdiction of the competent courts in <strong>Hyderabad, Telangana, India</strong>.
            </p>
          </section>

          <section class="legal-section" id="contact">
            <h2>9. Contact & Legal Enquiries</h2>
            <p>For any contractual questions, notices, or formal clarifications regarding these Terms, please contact:</p>
            <div class="legal-contact-card">
              <div class="contact-line">
                <i class="fa-solid fa-building"></i>
                <strong>Sunsolv Technologies — Legal & Contracts</strong>
              </div>
              <div class="contact-line">
                <i class="fa-solid fa-location-dot"></i>
                <span>Sunsolv HQ · Hyderabad, Telangana, India</span>
              </div>
              <div class="contact-line">
                <i class="fa-solid fa-envelope"></i>
                <span>Email: <a href="mailto:info@sunsolv.in">info&#64;sunsolv.in</a></span>
              </div>
              <div class="contact-line">
                <i class="fa-solid fa-phone"></i>
                <span>Phone: <a href="tel:+919676868607">+91 9676868607</a></span>
              </div>
            </div>
          </section>

          <div class="legal-footer-nav">
            <a routerLink="/security-compliance" class="legal-nav-btn">
              <span>View Security & Compliance</span>
              <i class="fa-solid fa-arrow-right"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .legal-page-wrapper {
      padding-bottom: 90px;
    }
    .legal-hero {
      background: radial-gradient(circle at 50% 0%, #023e8a 0%, #03045e 50%, #010224 100%);
      padding: 60px 24px 45px;
      border-bottom: 1px solid rgba(72, 202, 228, 0.2);
    }
    .legal-container {
      max-width: 960px;
      margin: 0 auto;
      padding: 0 20px;
    }
    .legal-breadcrumb {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 0.85rem;
      color: var(--c-cyan-300);
      margin-bottom: 18px;
    }
    .legal-breadcrumb a {
      color: var(--c-cyan-300);
      text-decoration: none;
    }
    .legal-breadcrumb a:hover {
      color: #ffffff;
    }
    .legal-breadcrumb .active {
      color: var(--c-cyan-100);
      font-weight: 700;
    }
    .legal-title {
      font-size: 2.6rem;
      font-weight: 900;
      color: #ffffff;
      margin-bottom: 10px;
      letter-spacing: -0.5px;
    }
    .legal-meta {
      font-size: 0.95rem;
      color: var(--c-cyan-200);
    }
    .legal-content-grid {
      margin-top: 40px;
    }
    .legal-main-body {
      background: rgba(3, 16, 68, 0.65);
      border: 1px solid rgba(72, 202, 228, 0.2);
      border-radius: 20px;
      padding: 44px;
      backdrop-filter: blur(20px);
      box-shadow: 0 10px 40px rgba(1, 2, 36, 0.6);
    }
    .legal-intro-box {
      font-size: 1.1rem;
      color: var(--c-cyan-100);
      line-height: 1.7;
      padding-bottom: 24px;
      margin-bottom: 30px;
      border-bottom: 1px solid rgba(72, 202, 228, 0.15);
    }
    .legal-section {
      margin-bottom: 36px;
    }
    .legal-section h2 {
      font-size: 1.45rem;
      font-weight: 800;
      color: #ffffff;
      margin-bottom: 16px;
      padding-bottom: 6px;
      border-bottom: 2px solid rgba(0, 180, 216, 0.3);
      display: inline-block;
    }
    .legal-section p {
      font-size: 0.98rem;
      color: var(--c-cyan-100);
      line-height: 1.7;
      margin-bottom: 14px;
    }
    .legal-section ul {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 12px;
      margin-left: 4px;
    }
    .legal-section ul li {
      position: relative;
      padding-left: 24px;
      font-size: 0.95rem;
      color: var(--c-cyan-100);
      line-height: 1.6;
    }
    .legal-section ul li::before {
      content: '■';
      position: absolute;
      left: 4px;
      color: var(--c-cyan-400);
      font-size: 0.75rem;
      top: 2px;
    }
    .legal-callout {
      margin-top: 20px;
      padding: 18px 22px;
      border-radius: 12px;
      display: flex;
      align-items: flex-start;
      gap: 16px;
    }
    .legal-callout.info {
      background: rgba(0, 119, 182, 0.25);
      border: 1px solid rgba(72, 202, 228, 0.4);
      color: var(--c-cyan-100);
    }
    .legal-callout i {
      font-size: 1.4rem;
      color: var(--c-cyan-400);
      margin-top: 2px;
    }
    .legal-contact-card {
      background: rgba(2, 62, 138, 0.3);
      border: 1px solid rgba(72, 202, 228, 0.25);
      border-radius: 14px;
      padding: 22px;
      display: flex;
      flex-direction: column;
      gap: 10px;
      margin-top: 14px;
    }
    .contact-line {
      display: flex;
      align-items: center;
      gap: 12px;
      font-size: 0.95rem;
      color: var(--c-cyan-100);
    }
    .contact-line i {
      color: var(--c-cyan-400);
      width: 18px;
    }
    .contact-line a {
      color: var(--c-cyan-300);
      text-decoration: none;
      font-weight: 700;
    }
    .contact-line a:hover {
      text-decoration: underline;
      color: #ffffff;
    }
    .legal-footer-nav {
      margin-top: 40px;
      padding-top: 24px;
      border-top: 1px solid rgba(72, 202, 228, 0.15);
      display: flex;
      justify-content: flex-end;
    }
    .legal-nav-btn {
      display: inline-flex;
      align-items: center;
      gap: 10px;
      background: linear-gradient(135deg, var(--c-blue-600), var(--c-cyan-500));
      color: var(--c-navy-900);
      font-weight: 800;
      padding: 12px 24px;
      border-radius: 10px;
      text-decoration: none;
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .legal-nav-btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 6px 20px rgba(0, 180, 216, 0.5);
    }
    @media (max-width: 768px) {
      .legal-title { font-size: 2rem; }
      .legal-main-body { padding: 24px 18px; }
      .legal-hero { padding: 40px 16px 30px; }
    }
  `]
})
export class TermsOfServiceComponent implements OnInit {
  constructor(private seo: SeoService) {}

  ngOnInit() {
    this.seo.setMetaTags({
      title: 'Terms of Service | Sunsolv Technologies',
      description: 'Terms of Service for Sunsolv Technologies. Read our terms regarding our Business Solution Finder, technical consulting, and custom engineering services.',
      url: 'https://sunsolv.com/terms-of-service'
    });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}
